TIMESTAMP = "dTimeStamp"

CIRCUIT_ID = "nTC"

FORWARD_PIPE_COOLANT_TEMP = "t1"
BACKWARD_PIPE_COOLANT_TEMP = "t2"

FORWARD_PIPE_COOLANT_VOLUME = "v1"
BACKWARD_PIPE_COOLANT_VOLUME = "v2"

FORWARD_PIPE_COOLANT_PRESSURE = "p1"
BACKWARD_PIPE_COOLANT_PRESSURE = "p2"
