TEMP_GRAPH_WEATHER_TEMP = "t"
TEMP_GRAPH_TEMP_AT_IN = "in_t"
TEMP_GRAPH_TEMP_AT_OUT = "out_t"

WEATHER_TEMP = "temp"
WEATHER_TIME = "time"
WEATHER_DATE = "date"

#Lysva columns
#HEATING_SYSTEM_CIRCUIT_ID = "nTC"
#HEATING_SYSTEM_FORWARD_PIPE_COOLANT_VOLUME = "v1"
#HEATING_SYSTEM_BACKWARD_PIPE_COOLANT_VOLUME = "v2"
#HEATING_SYSTEM_TIMESTAMP = "dTimeStamp"


#Chernushka columns
HEATING_SYSTEM_CIRCUIT_ID = "hs"
HEATING_SYSTEM_FORWARD_PIPE_COOLANT_VOLUME = "g1"
HEATING_SYSTEM_BACKWARD_PIPE_COOLANT_VOLUME = "g2"
HEATING_SYSTEM_TIMESTAMP = "d_timestamp"

HEATING_SYSTEM_FORWARD_PIPE_COOLANT_TEMP = "t1"
HEATING_SYSTEM_BACKWARD_PIPE_COOLANT_TEMP = "t2"
HEATING_SYSTEM_FORWARD_PIPE_COOLANT_PRESSURE = "p1"
HEATING_SYSTEM_BACKWARD_PIPE_COOLANT_PRESSURE = "p2"

